class ArticlesFragment:
    def html(self):
        return {
            "left": "<p>indexStudy-left (Generated by Class)</p>",
            "right": "<p>indexStudy-right (Generated by Class)</p>"
        }
