class SettingsFragment:
    def html(self):
        return {
            "left": "<p>settings-left (Generated by Class)</p>",
            "right": "<p>settings-right (Generated by Class)</p>"
        }
