class SubjectFragment:
    def html(self):
        return {
            "left": "<p>indexSubject-left (Generated by Class)</p>",
            "right": "<p>indexSubject-right (Generated by Class)</p>"
        }
